# Site settings
name: Max Bender
email: mab27@rice.edu
#canonical_url: ttps://github.com/MaxBender/maxbender
keywords: "Software Engineer, Data Analyst, Python, Java, .NET, R, Agile, Pair Programming"
skills: "Computer Science Student interested in product design and full-stack development"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/maxwellbender/
  - title: twitter
    url: https://twitter.com/mbender4242
  - title: instagram
    url: https://www.instagram.com/bendy.pics/
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
